version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_denominator:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_denominator
    outputs:
      highly_sensitive:
        cohort: output/input_denominator.csv

  generate_main:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_main
    outputs:
      highly_sensitive:
        cohort: output/input_main.csv

  describe:
    run: r:latest analysis/report.R
    needs: [generate_main]
    outputs:
      moderately_sensitive:
        age_plot1: output/age_plot1.png
        paca_count_plot: output/paca_no.png
        #paca_rate: output/paca_rate.png
        paca_count_table: output/paca_counts_pm.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2015-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv