version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_denominator_1:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_denominator --index-date-range "2015-01-01 to 2019-01-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/input*.feather
  
  generate_denominator_2:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_denominator --index-date-range "2019-02-01 to today by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inpu*.feather

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_denominator --skip-existing --output-dir=output/measures
    needs: 
      [
        generate_denominator_1,
        generate_denominator_2,
      ]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure*_rate.csv
  
  describe:
    run: r:latest analysis/analysis1.R
    needs: 
      [
        generate_study_population,
        # generate_measures,
      ]
    outputs:
      moderately_sensitive:
        Fig1: output/paca_time210222.png
  #       Tab1: output/paca_rate.csv
  #       Fig2: output/paca_rate_region.png
  #       Tab2: output/paca_rate_region.csv
  #       Fig3: output/paca_rate_IMD.png
  #       Tab3: output/paca_rate_IMD.csv
