version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_main:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_main
    outputs:
      highly_sensitive:
        cohort: output/input_main.csv

generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv

generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv