version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_main:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_main
    outputs:
      highly_sensitive:
        cohort: output/input_main.csv

generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

