version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_denominator_1:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_denominator --index-date-range "2015-01-01 to 2019-01-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/input*.feather
  
  generate_denominator_2:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_denominator --index-date-range "2019-02-01 to 2022-02-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inpu*.feather

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_denominator --skip-existing --output-dir=output/measures
    needs: 
      [
        generate_denominator_1,
        generate_denominator_2,
      ]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_registered*_rate.csv

  describe_data:
    run: r:latest analysis/analysis_counts_average.R
    needs: 
      [
        generate_study_population,
#?#         generate_measures,
      ]
    outputs:
      moderately_sensitive:
        Fig1: output/paca_time_table.png
        Fig2: output/paca_time_table_year.png
#?#         Fig3: output/paca_time_rates.png
#?#         Fig4: output/paca_time_rates_year.png
        Tab1: output/monthly_count.csv
        Tab2: output/monthly_median.csv
        Tab3: output/monthly_average.csv
