version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.feather

  generate_study_population_4:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2015-01-01 to 2016-12-01 by month" --skip-existing --output-dir=output/measures --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/measures/inp*.feather

  generate_study_population_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2017-01-01 to 2018-12-01 by month" --skip-existing --output-dir=output/measures --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/measures/inpu*.feather

  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2020-12-01 by month" --skip-existing --output-dir=output/measures --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/measures/input*.feather

  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.feather

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: 
      [
      generate_study_population_1,
      generate_study_population_2,
      generate_study_population_3,
      generate_study_population_4,
      ]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*_rate.csv
  
  describe:
    run: r:latest analysis/report.R
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        Fig1: output/paca_rate.png
        Tab1: output/paca_rate.csv
        Fig2: output/paca_rate_region.png
        Tab2: output/paca_rate_region.csv
        Fig3: output/paca_rate_IMD.png
        Tab3: output/paca_rate_IMD.csv

  # join_ethnicity_region:
  #   run: python:latest python analysis/join_ethnicity_region.py
  #   needs:
  #     [
  #     generate_study_population_1,
  #     generate_study_population_2,
  #     generate_study_population_3,
  #     generate_study_population_4,
  #     generate_ethnicity,
  #     ]
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/inp*.feather