version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_main:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_main
    outputs:
      highly_sensitive:
        cohort: output/input_main.csv


